name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: buildx
        uses: docker/setup-buildx-action@v2

      - name: login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Lint CSS with Stylelint
        run: |
          npm install -g stylelint stylelint-config-standard
          echo '{ "extends": "stylelint-config-standard" }' > .stylelintrc.json
          npx stylelint "**/*.css" || true

      - name: build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: selnter/cool-lab4-5:latest
          