name: Terraform CI/CD

on:
  push:
    branches: [ terra ]
  pull_request:
    branches: [ terra ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: GCP auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Init
        run: terraform init

      - name: Validate
        run: terraform validate

      - name: Plan
        id: plan
        run: terraform plan -var="project=${{ secrets.GCP_PROJECT_ID }}"

      - name: Apply
        if: github.ref == 'refs/heads/terra' && github.event_name == 'push'
        run: terraform apply -auto-approve -var="project=${{ secrets.GCP_PROJECT_ID }}"
